$axure.loadCurrentPage({
  "url":"以往运动信息.html",
  "generationDate":new Date(1429984958290.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6290f87f02a746a1af8b6040e5d6eae7",
    "type":"Axure:Page",
    "name":"以往运动信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8b8633fb99bd4a5cb26c88cb3a8b73ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":429,
              "height":839},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b4d0ec2551455381df35164b3e394e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":429,
                  "height":839},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"52e7829b72cc4557ad1c9c74f92890ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":185},
            "size":{
              "width":360,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b723bb6ecea44ee188946f6e90b3c12f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":185},
                "size":{
                  "width":360,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u2.png"}},
{
          "id":"10b195db6d70435bb8e25d8cc3846f0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":779},
            "size":{
              "width":360,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f403c44b3a7433eab78152cb94eb47b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":779},
                "size":{
                  "width":360,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u4.png"}},
{
          "id":"b0e76cfe2e034d6c8b2ba940572d962b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF101214},
{
                  "color":0xFF101214}]},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2091ea50d34a486c8a62e34afc743f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF101214},
{
                      "color":0xFF101214}]},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u6.png"}},
{
          "id":"6df9d856f6d74f14b219739c62b09c36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b423d84c81f1443299a0cc3d816dd50f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u8.png"}},
{
          "id":"9ced60ad8a4743ec95d8df81707a0af1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":74,
              "y":750},
            "size":{
              "width":76,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e0101a3433f42dab3233045187ff34e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":74,
                  "y":750},
                "size":{
                  "width":76,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/以往运动信息/u10.png"}},
{
          "id":"bce3158a0bcc498e98ce027c2f779b60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":150,
              "y":750},
            "size":{
              "width":76,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dcf74b32f3641a3af14472d11a578d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":150,
                  "y":750},
                "size":{
                  "width":76,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/以往运动信息/u10.png"}},
{
          "id":"4bd36a3b2ce147c68a482ebb28f72b7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":282,
              "y":750},
            "size":{
              "width":76,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50a1ede14b194b7392ad7710283de1b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":282,
                  "y":750},
                "size":{
                  "width":76,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/以往运动信息/u10.png"}},
{
          "id":"4036167bc9bf4ad49b79b23bcfdf42ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":358,
              "y":750},
            "size":{
              "width":76,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e2d64317554ca4a9e25b5bbe6ba94a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":358,
                  "y":750},
                "size":{
                  "width":76,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/以往运动信息/u10.png"}},
{
          "id":"d6e1682640674be8ad77989a05fcee25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":226,
              "y":730},
            "size":{
              "width":56,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49680b0f6054057b69fb4590166e39c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":226,
                  "y":730},
                "size":{
                  "width":56,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/以往运动信息/u18.png"}},
{
          "id":"3e407d1c48454a8b80d54617cc2523e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":429,
              "height":839},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62667da213f24629b17d034eb51ec99e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":429,
                  "height":839},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"41672c6bf571403088d1e2f70f49f2ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":185},
            "size":{
              "width":360,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76864e3c8ef046039c5789cb8f2c3822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":185},
                "size":{
                  "width":360,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u2.png"}},
{
          "id":"53d410949fbf4f32a8ac08de8bd7e6df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":779},
            "size":{
              "width":360,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8886bbae0f0040ad932088a4072e8e7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":779},
                "size":{
                  "width":360,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u4.png"}},
{
          "id":"9d8d925cffca46f6807af48a868d0f19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF101214},
{
                  "color":0xFF101214}]},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d5c5fe8cc4e4480960fcb892b93187c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF101214},
{
                      "color":0xFF101214}]},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u6.png"}},
{
          "id":"91febb0cffbc4a1696c223870d019855",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daa828db899840809399532da5ba591b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页面/u8.png"}},
{
          "id":"bd093cb4c2a1493792c80c408d6a771f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":90,
              "y":315},
            "size":{
              "width":330,
              "height":290},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab520ee34151470497a82c06e5e38d3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":90,
                  "y":315},
                "size":{
                  "width":330,
                  "height":290},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/以往运动信息/u30.png"}},
{
          "id":"eb0c2ceb228f448fb28e2433af863bcb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":355},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/以往运动信息/u32_line.png"}},
{
          "id":"22253d15f5214bdf82778f5e027e9b86",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":405},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/以往运动信息/u32_line.png"}},
{
          "id":"5be677ff44244426b48c7af2de738287",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":455},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/以往运动信息/u32_line.png"}},
{
          "id":"d8936dbb2a7c4120a3161da5468101c8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":505},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/以往运动信息/u32_line.png"}},
{
          "id":"fc15e6979846450c83ceabd1d3716e23",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":555},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/以往运动信息/u32_line.png"}},
{
          "id":"d1a377243e624816aecd49e92f3257f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":214,
              "y":281},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45e42bd440943f5ba100ef573700ffe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":214,
                  "y":281},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"124c33d815fb4768a7c4b07d4af8f61e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFF949494},
{
                  "color":0xFF949494}]},
            "location":{
              "x":206,
              "y":640},
            "size":{
              "width":96,
              "height":40},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bac345f1b63049c494852be540b466e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFF949494},
{
                      "color":0xFF949494}]},
                "location":{
                  "x":206,
                  "y":640},
                "size":{
                  "width":96,
                  "height":40},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页面",
                      "target":{
                        "targetType":"page",
                        "url":"主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页面/u71.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8b8633fb99bd4a5cb26c88cb3a8b73ad":{
      "scriptId":"u0"},
    "c0b4d0ec2551455381df35164b3e394e":{
      "scriptId":"u1"},
    "52e7829b72cc4557ad1c9c74f92890ff":{
      "scriptId":"u2"},
    "b723bb6ecea44ee188946f6e90b3c12f":{
      "scriptId":"u3"},
    "10b195db6d70435bb8e25d8cc3846f0b":{
      "scriptId":"u4"},
    "6f403c44b3a7433eab78152cb94eb47b":{
      "scriptId":"u5"},
    "b0e76cfe2e034d6c8b2ba940572d962b":{
      "scriptId":"u6"},
    "2091ea50d34a486c8a62e34afc743f63":{
      "scriptId":"u7"},
    "6df9d856f6d74f14b219739c62b09c36":{
      "scriptId":"u8"},
    "b423d84c81f1443299a0cc3d816dd50f":{
      "scriptId":"u9"},
    "9ced60ad8a4743ec95d8df81707a0af1":{
      "scriptId":"u10"},
    "0e0101a3433f42dab3233045187ff34e":{
      "scriptId":"u11"},
    "bce3158a0bcc498e98ce027c2f779b60":{
      "scriptId":"u12"},
    "9dcf74b32f3641a3af14472d11a578d7":{
      "scriptId":"u13"},
    "4bd36a3b2ce147c68a482ebb28f72b7a":{
      "scriptId":"u14"},
    "50a1ede14b194b7392ad7710283de1b4":{
      "scriptId":"u15"},
    "4036167bc9bf4ad49b79b23bcfdf42ae":{
      "scriptId":"u16"},
    "91e2d64317554ca4a9e25b5bbe6ba94a":{
      "scriptId":"u17"},
    "d6e1682640674be8ad77989a05fcee25":{
      "scriptId":"u18"},
    "c49680b0f6054057b69fb4590166e39c":{
      "scriptId":"u19"},
    "3e407d1c48454a8b80d54617cc2523e8":{
      "scriptId":"u20"},
    "62667da213f24629b17d034eb51ec99e":{
      "scriptId":"u21"},
    "41672c6bf571403088d1e2f70f49f2ef":{
      "scriptId":"u22"},
    "76864e3c8ef046039c5789cb8f2c3822":{
      "scriptId":"u23"},
    "53d410949fbf4f32a8ac08de8bd7e6df":{
      "scriptId":"u24"},
    "8886bbae0f0040ad932088a4072e8e7f":{
      "scriptId":"u25"},
    "9d8d925cffca46f6807af48a868d0f19":{
      "scriptId":"u26"},
    "6d5c5fe8cc4e4480960fcb892b93187c":{
      "scriptId":"u27"},
    "91febb0cffbc4a1696c223870d019855":{
      "scriptId":"u28"},
    "daa828db899840809399532da5ba591b":{
      "scriptId":"u29"},
    "bd093cb4c2a1493792c80c408d6a771f":{
      "scriptId":"u30"},
    "ab520ee34151470497a82c06e5e38d3e":{
      "scriptId":"u31"},
    "eb0c2ceb228f448fb28e2433af863bcb":{
      "scriptId":"u32"},
    "22253d15f5214bdf82778f5e027e9b86":{
      "scriptId":"u33"},
    "5be677ff44244426b48c7af2de738287":{
      "scriptId":"u34"},
    "d8936dbb2a7c4120a3161da5468101c8":{
      "scriptId":"u35"},
    "fc15e6979846450c83ceabd1d3716e23":{
      "scriptId":"u36"},
    "d1a377243e624816aecd49e92f3257f5":{
      "scriptId":"u37"},
    "d45e42bd440943f5ba100ef573700ffe":{
      "scriptId":"u38"},
    "124c33d815fb4768a7c4b07d4af8f61e":{
      "scriptId":"u39"},
    "bac345f1b63049c494852be540b466e1":{
      "scriptId":"u40"}}});