$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1429984957792.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4d31717fb94342c08f8e0fa25d0f4236",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2b0188d07864c8bbe1567ba0d1aa606",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":429,
              "height":839},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9e5998e28d45a88a76a2c8777c1e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":429,
                  "height":839},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"d5427c12df2544dfab5d2ca62a6c5954",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":185},
            "size":{
              "width":360,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18f485dd1574314a2a5b8bb40679f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":185},
                "size":{
                  "width":360,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u2.png"}},
{
          "id":"f93e5782f7754ede916e383936df0e6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":779},
            "size":{
              "width":360,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b85e74d58a3942b584a5320e0d382498",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":779},
                "size":{
                  "width":360,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u4.png"}},
{
          "id":"12c8ab8de6784e62bda4017e7ee99dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF101214},
{
                  "color":0xFF101214}]},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a72c2c39ab9423aa1d3978d212686fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF101214},
{
                      "color":0xFF101214}]},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u6.png"}},
{
          "id":"c4e833a49b1d4684b34a9d52bd9d23d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFA1A1A1},
{
                  "color":0xFFA1A1A1},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9}]},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab5ac31c7278437b956b296da4ba84ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFA1A1A1},
{
                      "color":0xFFA1A1A1},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u8.png"}},
{
          "id":"3b15593d4df043be9bbdf53c4334a90c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":451},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"9a84897770c144af89b3bbc3b50c29b3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":546},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"660e6ab599a846cc94f1c9eeefa32245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":458},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0ac00496c244f888de8ae701144cdf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":458},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a137eccbede47bd9dea1e74b5ef6182",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":553},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5c628a6b45f44c89b74e35df6677032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":553},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d36ba6261f8b480086d8c87310faf231",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF616163,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1C1D1F},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF222424}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF206E8B},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF35A6D0}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF424344},
            "location":{
              "x":216,
              "y":660},
            "size":{
              "width":94,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF828283}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"909dc6ec8ae241d4bea3b6c1076e3bc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF616163,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C1D1F},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF222424}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF206E8B},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF35A6D0}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF424344},
                "location":{
                  "x":216,
                  "y":660},
                "size":{
                  "width":94,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF828283}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆",
                      "target":{
                        "targetType":"page",
                        "url":"登陆.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u18.png",
            "mouseDown~":"images/登陆/u18_mouseDown.png",
            "disabled~":"images/登陆/u18_disabled.png"}},
{
          "id":"f3bd0cd5aa234c44ac57dab830a5f616",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":594},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"2858768d39924c27b790806939e3daf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":601},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64f6e5942e940cfa5a7ec6a95b0297e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":601},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64f8d7b739d5447998f7873a404e01af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":499},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"3fa5d5045b3d42b9af87d6a8ab51491e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":506},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f142e041b5492c96a3836c2b6fe391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":506},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e696ce034ab349b4bba2a85f8b4f7954",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194.5,
              "y":284},
            "size":{
              "width":137,
              "height":136},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"65"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd9ff2d76914d2ba8a8642c44dccf8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194.5,
                  "y":284},
                "size":{
                  "width":137,
                  "height":136},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"65"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f2b0188d07864c8bbe1567ba0d1aa606":{
      "scriptId":"u0"},
    "fd9e5998e28d45a88a76a2c8777c1e55":{
      "scriptId":"u1"},
    "d5427c12df2544dfab5d2ca62a6c5954":{
      "scriptId":"u2"},
    "b18f485dd1574314a2a5b8bb40679f4a":{
      "scriptId":"u3"},
    "f93e5782f7754ede916e383936df0e6a":{
      "scriptId":"u4"},
    "b85e74d58a3942b584a5320e0d382498":{
      "scriptId":"u5"},
    "12c8ab8de6784e62bda4017e7ee99dda":{
      "scriptId":"u6"},
    "1a72c2c39ab9423aa1d3978d212686fd":{
      "scriptId":"u7"},
    "c4e833a49b1d4684b34a9d52bd9d23d7":{
      "scriptId":"u8"},
    "ab5ac31c7278437b956b296da4ba84ae":{
      "scriptId":"u9"},
    "3b15593d4df043be9bbdf53c4334a90c":{
      "scriptId":"u10"},
    "9a84897770c144af89b3bbc3b50c29b3":{
      "scriptId":"u11"},
    "660e6ab599a846cc94f1c9eeefa32245":{
      "scriptId":"u12"},
    "c0ac00496c244f888de8ae701144cdf6":{
      "scriptId":"u13"},
    "5a137eccbede47bd9dea1e74b5ef6182":{
      "scriptId":"u14"},
    "b5c628a6b45f44c89b74e35df6677032":{
      "scriptId":"u15"},
    "d36ba6261f8b480086d8c87310faf231":{
      "scriptId":"u16"},
    "909dc6ec8ae241d4bea3b6c1076e3bc5":{
      "scriptId":"u17"},
    "f3bd0cd5aa234c44ac57dab830a5f616":{
      "scriptId":"u18"},
    "2858768d39924c27b790806939e3daf8":{
      "scriptId":"u19"},
    "f64f6e5942e940cfa5a7ec6a95b0297e":{
      "scriptId":"u20"},
    "64f8d7b739d5447998f7873a404e01af":{
      "scriptId":"u21"},
    "3fa5d5045b3d42b9af87d6a8ab51491e":{
      "scriptId":"u22"},
    "94f142e041b5492c96a3836c2b6fe391":{
      "scriptId":"u23"},
    "e696ce034ab349b4bba2a85f8b4f7954":{
      "scriptId":"u24"},
    "ccd9ff2d76914d2ba8a8642c44dccf8a":{
      "scriptId":"u25"}}});