$axure.loadCurrentPage({
  "url":"登陆.html",
  "generationDate":new Date(1429984957712.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9fd788200ad0478b95e36b3502abfab3",
    "type":"Axure:Page",
    "name":"登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"08a255f0d1aa4dcd9adfdf971d4535e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":429,
              "height":839},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94dca837d91d45f395ce5c062df73a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":429,
                  "height":839},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"9b58ba8faa394c00ba9861f46f300825",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":185},
            "size":{
              "width":360,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ea971c41d545ea8e6d15722bd32777",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":185},
                "size":{
                  "width":360,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u2.png"}},
{
          "id":"d5d97ed1346e4a9996d63366f584687e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":779},
            "size":{
              "width":360,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b4e6e930f864a789a557de69a01c791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":779},
                "size":{
                  "width":360,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u4.png"}},
{
          "id":"66abbdfc50f84462bb172949f9420d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF000000},
{
                  "color":0xFF000000},
{
                  "color":0xFF101214},
{
                  "color":0xFF101214}]},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f08cced0e441e6ad853c39879de45d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF000000},
{
                      "color":0xFF000000},
{
                      "color":0xFF101214},
{
                      "color":0xFF101214}]},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u6.png"}},
{
          "id":"f2744202d06b4e7e867bfcc05a2bb915",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFA1A1A1},
{
                  "color":0xFFA1A1A1},
{
                  "color":0xFFC9C9C9},
{
                  "color":0xFFC9C9C9}]},
            "location":{
              "x":74,
              "y":209},
            "size":{
              "width":360,
              "height":570},
            "borderFill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7baaea41ee5b4f7bad4811e713c2bbc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFA1A1A1},
{
                      "color":0xFFA1A1A1},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]},
                "location":{
                  "x":74,
                  "y":209},
                "size":{
                  "width":360,
                  "height":570},
                "borderFill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u8.png"}},
{
          "id":"e36682e5043e4110aa0c3a7c3334b723",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":489},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"3ab99af779384a4eb8c93a03d927e970",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":537},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"1d36098deaf540638f204daea350de23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":496},
            "size":{
              "width":40,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4cd78bf7c64685a38dd7b7e28f3c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":496},
                "size":{
                  "width":40,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"625f346f469c4344b4b83ad2d482f926",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":544},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d35955b924c4595b63af34377696d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":544},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e72a6fba439c453f89d5cfbb38d1cb5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF616163,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1C1D1F},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF222424}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF206E8B},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF35A6D0}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF424344},
            "location":{
              "x":166,
              "y":608},
            "size":{
              "width":91,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF828283}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d7cdea150d844649b62a2da2236faab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF616163,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C1D1F},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF222424}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF206E8B},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF35A6D0}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF424344},
                "location":{
                  "x":166,
                  "y":608},
                "size":{
                  "width":91,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF828283}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页面",
                      "target":{
                        "targetType":"page",
                        "url":"主页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u16.png",
            "mouseDown~":"images/登陆/u16_mouseDown.png",
            "disabled~":"images/登陆/u16_disabled.png"}},
{
          "id":"557d0f73a06a42ecaa2a8621bdfb8848",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Roboto Regular', 'Roboto'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF616163,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1C1D1F},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF222424}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF206E8B},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF35A6D0}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF424344},
            "location":{
              "x":277,
              "y":608},
            "size":{
              "width":94,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF828283}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e760819bd074b2baacac05223198950",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Roboto Regular', 'Roboto'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF616163,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1C1D1F},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF222424}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF206E8B},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF35A6D0}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF424344},
                "location":{
                  "x":277,
                  "y":608},
                "size":{
                  "width":94,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF828283}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u18.png",
            "mouseDown~":"images/登陆/u18_mouseDown.png",
            "disabled~":"images/登陆/u18_disabled.png"}},
{
          "id":"1d2b82aa090346f0b81be00b135d279a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":308},
            "size":{
              "width":137,
              "height":136},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"65"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472694361b584b9494480a168a72344f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":186,
                  "y":308},
                "size":{
                  "width":137,
                  "height":136},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"65"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "08a255f0d1aa4dcd9adfdf971d4535e4":{
      "scriptId":"u0"},
    "94dca837d91d45f395ce5c062df73a5f":{
      "scriptId":"u1"},
    "9b58ba8faa394c00ba9861f46f300825":{
      "scriptId":"u2"},
    "d2ea971c41d545ea8e6d15722bd32777":{
      "scriptId":"u3"},
    "d5d97ed1346e4a9996d63366f584687e":{
      "scriptId":"u4"},
    "1b4e6e930f864a789a557de69a01c791":{
      "scriptId":"u5"},
    "66abbdfc50f84462bb172949f9420d51":{
      "scriptId":"u6"},
    "b1f08cced0e441e6ad853c39879de45d":{
      "scriptId":"u7"},
    "f2744202d06b4e7e867bfcc05a2bb915":{
      "scriptId":"u8"},
    "7baaea41ee5b4f7bad4811e713c2bbc6":{
      "scriptId":"u9"},
    "e36682e5043e4110aa0c3a7c3334b723":{
      "scriptId":"u10"},
    "3ab99af779384a4eb8c93a03d927e970":{
      "scriptId":"u11"},
    "1d36098deaf540638f204daea350de23":{
      "scriptId":"u12"},
    "ac4cd78bf7c64685a38dd7b7e28f3c79":{
      "scriptId":"u13"},
    "625f346f469c4344b4b83ad2d482f926":{
      "scriptId":"u14"},
    "3d35955b924c4595b63af34377696d10":{
      "scriptId":"u15"},
    "e72a6fba439c453f89d5cfbb38d1cb5a":{
      "scriptId":"u16"},
    "9d7cdea150d844649b62a2da2236faab":{
      "scriptId":"u17"},
    "557d0f73a06a42ecaa2a8621bdfb8848":{
      "scriptId":"u18"},
    "4e760819bd074b2baacac05223198950":{
      "scriptId":"u19"},
    "1d2b82aa090346f0b81be00b135d279a":{
      "scriptId":"u20"},
    "472694361b584b9494480a168a72344f":{
      "scriptId":"u21"}}});